services:
  mongodb:
    image: mongo:latest
    container_name: chat-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: chat-backend
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URL=mongodb://mongodb:27017/chat-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data: