export const host = "http://localhost:5000";
export const loginRoute = `${host}/api/auth/login`;
export const registerRoute = `${host}/api/auth/register`;
export const logoutRoute = `${host}/api/auth/logout`;
export const allUsersRoute = `${host}/api/auth/allusers`;
export const sendMessageRoute = `${host}/api/messages/addmsg`;
export const recieveMessageRoute = `${host}/api/messages/getmsg`;
export const setAvatarRoute = `${host}/api/auth/setavatar`;
export const getAvatarsRoute = `${host}/api/auth/avatars`;
export const savePhq9Route = `${host}/api/auth/phq9/save`;
export const getPhq9Route = (id) => `${host}/api/auth/phq9/${id}`;
